FROM ruby:3.1.2-slim

WORKDIR /app

RUN bash -c "set -o pipefail && apt-get update \
  && apt-get install -y --no-install-recommends build-essential curl git libmariadb-dev graphviz \
  && curl -sSL https://deb.nodesource.com/setup_16.x | bash - \
  && curl -sSL https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
  && echo 'deb https://dl.yarnpkg.com/debian/ stable main' | tee /etc/apt/sources.list.d/yarn.list \
  && apt-get update && apt-get install -y --no-install-recommends nodejs yarn \
  && rm -rf /var/lib/apt/lists/* /usr/share/doc /usr/share/man \
  && apt-get clean"
  
ARG SINATRA_ENV="production"
ENV SINATRA_ENV="${SINATRA_ENV}"

COPY Gemfile* ./
RUN bundle check || bundle install --jobs "$(nproc)"

COPY . .

ENTRYPOINT ["sh", "./entrypoint.sh"]

EXPOSE 5000

CMD ["bundle", "exec", "rackup", "config.ru", "--host", "0.0.0.0"]